### ISSUE TITLE
Should root have admin permissions to all corpora / media / layers?

### ISSUE THREAD

**Issue by francoisromain** [camomile-project/camomile-server#81]
When a `corpus`, `media` or `layer` is created by a user, the root user has no admin access to these. If the user remove himself the `ADMIN` permission on one of these resource, it can result in a situation where no user has admin permission to it, even root.

It could be good to give root an ADMIN access to any resource by default, so that the permissions could be set back, or deleted even if no user has permission to it.

**Comment by hbredin** [comment]
`root` does have the equivalent of `ADMIN` access to any resource:
https://github.com/camomile-project/camomile-server/blob/e7625eecd2320198f2f133baeb51928406f9dcad/controllers/utils.js#L153-L158

It is just not explicitly listed in the list of permissions because it is not considered a regular user:  it should only be used as a last resort. 

For the same reason, `root` is not listed in the list of users (`GET /user`):
https://github.com/camomile-project/camomile-server/blob/e7625eecd2320198f2f133baeb51928406f9dcad/controllers/User.js#L38

**Comment by francoisromain** [comment]
Ok I got it. I fixed it accordingly in the ui-library https://github.com/francoisromain/camomile-ui/blob/b5d8deb55fd14d572e02e1e102f4cc129c4052e0/src/store/camomile/user.js#L115-L117
